# Day 2
## 3. 이산확률변수
### 이항분포

In [1]:
from scipy.stats import binom

# 확률질량함수 : binom.pmf

## 동전을 10번 던져서 앞면이 3번 나올 확률
binom.pmf(k=3, n=10, p=0.5)

0.1171875

In [3]:
# 누적분포함수 : binom.cdf

## 동전을 10번 던져서 앞면이 6번 이하로 나올 확률
print(binom.cdf(k=6, n=10, p=0.5))

## 동전을 10번 던져서 앞면이 7번 이상 나올 확률
print(1 - binom.cdf(k=6, n=10, p=0.5))

0.828125
0.171875


In [4]:
# 분위수 :  binom.ppf

## 누적확률이 0.3 이상이 되는 x
binom.ppf(0.3, n=10, p=0.5)

4.0

In [5]:
# 난수 : binom.rvs

## 동전을 10번 던지는 실험을 30번 반복
binom.rvs(n=10, p=0.5, size=30)

array([5, 2, 6, 4, 3, 6, 5, 4, 3, 3, 5, 6, 2, 6, 2, 5, 7, 6, 7, 7, 4, 8,
       2, 7, 4, 4, 6, 7, 3, 6])

### 초기하분포

In [9]:
from scipy.stats import hypergeom

# 확률질량함수 : hypergeom.pmf

## N = 1,000, A = 200, n = 50  -> P(X = 10)
hypergeom.pmf(10, 1000, 200, 50)

0.14344796941100665

In [10]:
# 누적분포함수 : hypergeom.cdf

## N = 1,000, A = 200, n = 50  -> P(X <= 10)
print(hypergeom.cdf(10, 1000, 200, 50))

## N = 1,000, A = 200, n = 50  -> P(X > 10)
print(1 - hypergeom.cdf(10, 1000, 200, 50))

0.5843039735718374
0.4156960264281626


In [11]:
# 분위수 :  hypergeom.ppf

## 누적확률이 0.5 이상이 되는 x
hypergeom.ppf(0.5, 1000, 200, 50)

10.0

In [13]:
# 난수 : hypergeom.rvs

## 모의실험을 25번 반복하는 경우
hypergeom.rvs(1000, 200, 50, size = 25)

array([10, 12, 13,  9,  7, 18, 14,  8, 10, 13, 12,  8, 12,  7, 15, 10,  6,
       11, 10,  9, 11, 11,  7, 15,  7])

### 포아송분포

In [14]:
from scipy.stats import poisson

# 확률질량함수 : poisson.pmf

## mu = 5  -> P(X = 7)
poisson.pmf(7, 5)

0.10444486295705395

In [15]:
# 누적분포함수 : poisson.cdf

## mu = 5  -> P(X <= 7)
print(poisson.cdf(7,5))

## mu = 5  -> P(X > 7)
print(1 - poisson.cdf(7,5))

0.8666283259299925
0.1333716740700075


In [16]:
# 분위수 :  poisson.ppf

## 누적확률이 0.7 이상이 되는 x
poisson.ppf(0.7, 5)

6.0

In [17]:
# 난수 : poisson.rvs

## 모의실험을 30번 반복하는 경우
poisson.rvs(5, size = 30)

array([10,  1, 10,  5,  9,  3,  3,  6,  5,  1,  3,  4,  3,  4,  8,  8,  4,
        5,  1,  8,  5,  8,  5,  9,  2,  2,  3,  4,  4,  4])

## 4. 연속형 확률분포
### 정규분포

In [18]:
from scipy.stats import norm

# 확률밀도함수 : norm.pdf

## mu = 42, sigma = 5  -> f(X = 40)
norm.pdf(40, 42, 5)

0.07365402806066466

In [19]:
# 누적분포함수 : norm.cdf

## mu = 42, sigma = 5  -> P(X <= 54)
print(norm.cdf(54, 42, 5))

## mu = 42, sigma = 5  -> P(40 <= X <= 54)
print(norm.cdf(54, 42, 5)-norm.cdf(40, 42, 5))

0.9918024640754038
0.647224205685728


In [21]:
# 분위수 :  norm.ppf

## 누적확률이 0.9 이상이 되는 x
norm.ppf(0.9, 42, 5)

48.407757827723

In [22]:
# 난수 : norm.rvs

## 모의실험을 7번 반복하는 경우
norm.rvs(42, 5, size = 7)

array([39.79713819, 42.36614093, 37.72709114, 48.39961748, 48.05154957,
       40.61101928, 41.43909474])

## 5. 표본분포
### t-분포

In [23]:
from scipy.stats import t

# 확률밀도함수 : t.pdf

## 자유도 = 5  -> f(X = 1.64)
t.pdf(1.64, 5)

0.10435965219804019

In [26]:
# 누적분포함수 : t.cdf

## 자유도 = 5  -> P(X <= 1.64)
print(t.cdf(1.64, 5))

## 자유도 = 5  -> P(1.32 <= X <= 1.64)
print(t.cdf(1.64, 5)-norm.cdf(1.32, 5))

0.9190351742553341
0.9189185572785187


In [27]:
# 분위수 :  t.ppf

## 누적확률이 0.9 이상이 되는 x
t.ppf(0.9, 5)

1.4758840487820273

In [28]:
# 난수 : t.rvs

## 모의실험을 10번 반복하는 경우
t.rvs(5, size = 10)

array([-1.06501747, -0.49362809, -0.52886205,  0.19986489, -0.60136868,
        0.14805449, -1.08972897, -1.80858368,  1.73917365,  0.55275992])

### 카이제곱분포

In [29]:
from scipy.stats import chi2

# 확률밀도함수 : chi2.pdf

## 자유도 = 3  -> f(X = 1)
chi2.pdf(1, 3)

0.24197072451914337

In [31]:
# 누적분포함수 : chi2.cdf

## 자유도 = 3  -> P(X <= 1)
print(chi2.cdf(1, 3))

0.19874804309879915


In [33]:
# 분위수 :  chi2.ppf

## 누적확률이 0.9 이상이 되는 x
chi2.ppf(0.9, 3)

6.251388631170325

In [34]:
# 난수 : chi2.rvs

## 모의실험을 10번 반복하는 경우
chi2.rvs(3, size = 10)

array([0.53879067, 1.94034718, 0.59063437, 6.17315837, 3.71236181,
       0.9996565 , 3.1007916 , 2.26137182, 6.08520028, 3.20293531])

### F-분포

In [35]:
from scipy.stats import f

# 확률밀도함수 : f.pdf

## 자유도 = (5, 5)  -> f(X = 2)
f.pdf(2, 5, 5)

0.15808023109480038

In [36]:
# 누적분포함수 : f.cdf

## 자유도 = (5, 5)  -> P(X <= 2)
print(f.cdf(2, 5, 5))

0.7674886808696213


In [37]:
# 분위수 :  f.ppf

## 누적확률이 0.9 이상이 되는 x
f.ppf(0.9, 5, 5)

3.4529822480379053

In [38]:
# 난수 : f.rvs

## 모의실험을 10번 반복하는 경우
f.rvs(5, 5, size = 10)

array([1.29724372, 2.57738722, 0.56850756, 0.27524651, 0.59551316,
       0.2873826 , 0.40399194, 1.52338059, 0.474833  , 6.46241826])

## 6. 통계적 추정
### 모평균에 대한 신뢰구간


In [40]:
# Csi 데이터 불러오기

import pandas as pd
Csi = pd.read_csv("/content/drive/MyDrive/단기기초통계/Day2/data/Csi.csv")
Csi.head()

ID  Index
0   1     75
1   2     63
2   3     49
3   4     86
4   5     53

- 직접계산

In [44]:
from scipy.stats import t
import numpy as np

# n: 표본의 개수
n = Csi.Index.size

# Csi.Index의 평균
mean = np.mean(Csi.Index)

# 표준오차 계산
sd = np.std(Csi.Index, ddof = 1)/np.sqrt(n)

# 오차한계 계산
limit = t.ppf((1-0.05/2), n-1)*sd

# 신뢰구간 계산
print(mean-limit, mean+limit)

67.53175533702299 77.108244662977


- 패키지 이용

In [47]:
import statsmodels.stats.api as sms

# 평균
print(sms.DescrStatsW(Csi.Index).mean)

# 표준편차 : 분모(n-ddof)
print(sms.DescrStatsW(Csi.Index, ddof = 1).std)

# 신뢰구간
print(sms.DescrStatsW(Csi.Index).tconfint_mean())

72.32
11.600000000000001
(67.53175533702299, 77.108244662977)


### 모비율에 대한 신뢰구간
- 패키지 이용

In [48]:
from statsmodels.stats.proportion import proportion_confint

print("표본비율: p = ", 250/400)
proportion_confint(count = 250, nobs = 400, alpha = 0.05, method = "beta")

표본비율: p =  0.625


(0.5755217886614248, 0.67261376127048)

- 정규근사 신뢰구간


In [49]:
from scipy.stats import norm
import numpy as np

norm.interval(0.95, 250/400, scale = np.sqrt(250/400*(1-250/400)/400))

(0.5775568258044378, 0.6724431741955622)

In [50]:
proportion_confint(count = 250, nobs = 400, alpha = 0.05, method = "normal")

(0.5775568258044377, 0.6724431741955623)

### 모분산에 대한 신뢰구간

In [52]:
from scipy.stats import bayes_mvs

# 평균, 분산, 표준편차 각각의 신뢰구간 계산
mean_ci, var_ci, std_ci = bayes_mvs(Csi.Index, alpha = 0.95)
print(var_ci)
print(std_ci)

Variance(statistic=146.79272727272726, minmax=(82.04028250979714, 260.41455376108695))
Std_dev(statistic=11.978951328828686, minmax=(9.057609094556748, 16.137365143079798))
